version: "3.3"
services:
  pg:
    container_name: pg
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "messenger"
      POSTGRES_USER: "messenger_admin"
      POSTGRES_PASSWORD: "123654"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api
    image: "${CI_REGISTRY_IMAGE}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    environment:
       POSTGRES_DB: "messenger"
       POSTGRES_USER: "messenger_admin"
       POSTGRES_PASSWORD: "123654"
       POSGRES_HOSTS: "pg:5432"
    depends_on:
      - pg

volumes:
  postgres_data:
    driver: local