create table found_messages
(
    id      int8 generated by default as identity,
    chat_id varchar(255),
    text    varchar(255),
    task_id int8 not null,
    primary key (id)
);
alter table if exists found_messages
    add constraint FKfvycm0f6e06tu87guql49marb foreign key (task_id) references tasks;